### PR TITLE
Feature/update webhook structure

### PR DESCRIPTION
**Pull request by benmorana**
### Motivation

As of April this year, collections became part of the webhook notification model (https://docs.kontent.ai/changelog/product-changelog?show=webhooks#a-collections-are-now-in-webhook-notifications). This PR updates the typing and tests to include the collection property in the webhook item structure.

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### CODE REVIEW

**Comment by benmorana** [comment]
@Enngage - This is my first Kentico Kontent PR, so please don't hesitate to let me know if I've missed anything 😄

**Comment by Simply007** [comment]
Hey @benmorana!

thank you for the pull request! It is great to see these kinds of contributions from Kontent community!

@Enngage is on a vacation today. He will take a look as soon as he can :-)

**Review by Enngage — APPROVED** [review]
LGTM, thanks for the PR! :)

**Comment by Enngage** [comment]
I've released `1.2.0` on npm with this update

**Comment by benmorana** [comment]
Awesome! Thanks @Enngage 😄

**Pull request merged**
